	--DROP TABLES AND STORED PROCEDURES IF THEY EXIST
	GO
	BEGIN
	IF OBJECT_ID(N'dbo.TempTblDogs', N'U')											IS NOT NULL DROP TABLE TempTblDogs;
	IF OBJECT_ID(N'dbo.TempTblDogHealth', N'U')										IS NOT NULL DROP TABLE TempTblDogHealth;
	IF OBJECT_ID(N'dbo.TempTblDogPedigree', N'U')									IS NOT NULL DROP TABLE TempTblDogPedigree;
	IF OBJECT_ID(N'dbo.TblDogHealth', N'U')											IS NOT NULL DROP TABLE TblDogHealth;
	IF OBJECT_ID(N'dbo.TblDogPedigree', N'U')										IS NOT NULL DROP TABLE TblDogPedigree;
	IF OBJECT_ID(N'dbo.TblDogs', N'U')												IS NOT NULL DROP TABLE TblDogs;
	IF EXISTS (SELECT 1 FROM sys.procedures WHERE NAME = 'spDelete_Dog')			DROP PROCEDURE spDelete_Dog;
	IF EXISTS (SELECT 1 FROM sys.procedures WHERE NAME = 'spInsert_Into_TblDogs_TblDogHealth_TblDogPedigree')	DROP PROCEDURE spInsert_Into_TblDogs_TblDogHealth_TblDogPedigree;

	END
	GO

	--CREATE TEMPORARY TABLes WITHOUT CONSTRAINTS FOR ASSURING DATA INTEGRITY WHEN INSERTING
	GO
	BEGIN
	CREATE TABLE TempTblDogs
(	PedigreeID		NVARCHAR(50)	,
	DateOfBirth		NVARCHAR(50)	,
	Alive			NVARCHAR(1)		,
	Sex				NVARCHAR(1)		,
	Colour			NVARCHAR(10)	,
	AK				NVARCHAR(50)	,
	BreedStatus		NVARCHAR(1)		,
	DKTitles		NVARCHAR(200)	,
	Titles			NVARCHAR(200)	,
	[Name]			NVARCHAR(50)	,
	Picture			NVARCHAR(50)	,
	);
	CREATE TABLE TempTblDogHealth
(	PedigreeID		NVARCHAR(50)	,
	HD				NVARCHAR(15)	,
	AD				NVARCHAR(15)	,
	HZ				NVARCHAR(15)	,
	SP				NVARCHAR(15)	,
	);
	CREATE TABLE TempTblDogPedigree
(	PedigreeID		NVARCHAR(50)	,
	Father			NVARCHAR(50)	,
	Mother			NVARCHAR(50)	,
	TattooNo		NVARCHAR(50)	,
	[Owner]			NVARCHAR(50)	,
	);

	--CREATE TABLES WITH CONSTRAINTS (ACTUAL TABLES)
	CREATE TABLE TblDogs
(	PedigreeID		NVARCHAR(50)	NOT NULL,
	DateOfBirth		NVARCHAR(50)	,
	Alive			NVARCHAR(1)		,
	Sex				NVARCHAR(1)		,
	Colour			NVARCHAR(10)	,
	AK				NVARCHAR(50)	,
	BreedStatus		NVARCHAR(1)		,
	DKTitles		NVARCHAR(200)	,
	Titles			NVARCHAR(200)	,
	[Name]			NVARCHAR(50)	,
	Picture			NVARCHAR(50)	,
	CONSTRAINT PK_TblDogs_PedigreeID PRIMARY KEY (PedigreeID)
	);
	CREATE TABLE TblDogHealth
(	PedigreeID		NVARCHAR(50)	NOT NULL,
	HD				NVARCHAR(15)	,
	AD				NVARCHAR(15)	,
	HZ				NVARCHAR(15)	,
	SP				NVARCHAR(15)	,
	CONSTRAINT PK_TblDogHealth_PedigreeID PRIMARY KEY (PedigreeID),
	CONSTRAINT FK_TblDogHealth_PedigreeID FOREIGN KEY (PedigreeID) REFERENCES TblDogs(PedigreeID)
	);
	CREATE TABLE TblDogPedigree
(	PedigreeID		NVARCHAR(50)	NOT NULL,
	Father			NVARCHAR(50)	,
	Mother			NVARCHAR(50)	,
	TattooNo		NVARCHAR(50)	,
	[Owner]			NVARCHAR(50)	,
	CONSTRAINT PK_TblDogPedigree_PedigreeID PRIMARY KEY (PedigreeID),
	CONSTRAINT FK_TblDogPedigree_PedigreeID FOREIGN KEY (PedigreeID) REFERENCES TblDogs(PedigreeID)
	);
	END
	GO

	--TRIGGERS FOR ALL TEMOORARY TABLES ARE DEFINED TO ENSURE DATA INTEGRITY AND INSERT INTO THE ACTUAL TABLES
	--TRIGGER ON TempTblDogs TO HANDLE DUPLICAETE ROWS
	GO
	CREATE TRIGGER trBulkInsert_on_TempTblDogs ON TempTblDogs AFTER INSERT
	AS
	DELETE PedigreeID FROM
	(SELECT *, DupRank = ROW_NUMBER() OVER
	(PARTITION BY PedigreeID ORDER BY (SELECT NULL)
	)FROM TempTblDogs) AS PedigreeID WHERE DupRank > 1

	--INSERT INTO TblDogs FROM TempTblDogs IF THE RECORDS DO NOT MATCH ALREADY EXISTING RECORDS
	INSERT INTO TblDogs
	SELECT * FROM TempTblDogs
	WHERE NOT EXISTS (SELECT PedigreeID FROM TblDogs Where TblDogs.PedigreeID = TempTblDogs.PedigreeID)

	--TRUNCATE TEMPTABLE
	TRUNCATE TABLE TempTblDogs;
	GO
	
	--INSERT INTO TblDogHealth FROM TempTblDogHealth IF THE RECORDS DO NOT MATCH ALREADY EXISTING RECORDS
	GO
	CREATE TRIGGER trBulkInsert_on_TempTblDogHealth ON TempTblDogHealth AFTER INSERT
	AS	
	DELETE PedigreeID FROM
	(SELECT *, DupRank = ROW_NUMBER() OVER
	(PARTITION BY PedigreeID ORDER BY (SELECT NULL)
	)FROM TempTblDogHealth) AS PedigreeID WHERE DupRank > 1

	--INSERT CONDITIONALLY JOINING TblDogs AND TempTblDogPedigree AND CHECKING FOR ALREADY EXISTING RECORDS
	INSERT INTO TblDogHealth
	SELECT TblDogs.PedigreeID, HD, AD, HZ, SP FROM TempTblDogHealth JOIN TblDogs ON TblDogs.PedigreeID = TempTblDogHealth.PedigreeID
	WHERE NOT EXISTS (SELECT PedigreeID FROM TblDogHealth Where TblDogHealth.PedigreeID = TempTblDogHealth.PedigreeID)

	--TRUNCATE TEMPORARY TABLE
	TRUNCATE TABLE TempTblDogHealth;
	GO

	--INSERT INTO TblDogPedigree FROM TempTblDogPedigree IF THE RECORDS DO NOT MATCH ALREADY EXISTING RECORDS
	GO
	CREATE TRIGGER trBulkInsert_on_TempTblDogPedigree ON TempTblDogPedigree AFTER INSERT
	AS
	DELETE PedigreeID FROM
	(SELECT *, DupRank = ROW_NUMBER() OVER
	(PARTITION BY PedigreeID ORDER BY (SELECT NULL)
	)FROM TempTblDogPedigree) AS PedigreeID WHERE DupRank > 1
	
	--INSERT CONDITIONALLY JOINING TblDogs AND TempTblDogPedigree AND CHECKING FOR ALREADY EXISTING RECORDS
	INSERT INTO TblDogPedigree
	SELECT TblDogs.PedigreeID, Father, Mother, TattooNo, [Owner] FROM TempTblDogPedigree JOIN TblDogs ON TblDogs.PedigreeID = TempTblDogPedigree.PedigreeID
	WHERE NOT EXISTS (SELECT PedigreeID FROM TblDogPedigree Where TblDogPedigree.PedigreeID = TempTblDogPedigree.PedigreeID)

	--TRUNCATE TEMPORARY TABLE
	TRUNCATE TABLE TempTblDogPedigree;
	GO

	--STORED PROCEDURE FOR CLEARING ALL TABLES (CAN'T TRUNCATE TblDogs AS IT CONTAINS THR FOREIGN KEY REFERENCE FOR THE OTHER TABLES)
	--DELETION IS THUS DONE RECORD-WISE AND NOT BY TRUNCATING OR CLEARING WHOLE TABLES
	GO
	CREATE PROCEDURE spDelete_Dog @PedigreeID NVARCHAR(50)
	AS
	DELETE FROM TblDogHealth WHERE PedigreeID = @PedigreeID
	DELETE FROM TblDogPedigree WHERE PedigreeID = @PedigreeID
	DELETE FROM TblDogs WHERE PedigreeID = @PedigreeID
	GO

	--STORED PROCEDURE FOR INSERT INTO ALL TABLES
	GO
	CREATE PROCEDURE spInsert_Into_TblDogs_TblDogHealth_TblDogPedigree
	@1			NVARCHAR(50)	,
	@2			NVARCHAR(50)	,
	@3			NVARCHAR(1)		,
	@4			NVARCHAR(1)		,
	@5			NVARCHAR(10)	,
	@6			NVARCHAR(50)	,
	@7			NVARCHAR(1)		,
	@8			NVARCHAR(200)	,
	@9			NVARCHAR(200)	,
	@10			NVARCHAR(50)	,
	@11			NVARCHAR(15)	,
	@12			NVARCHAR(15)	,
	@13			NVARCHAR(15)	,
	@14			NVARCHAR(15)	,
	@15			NVARCHAR(50)	,
	@16			NVARCHAR(50)	,
	@17			NVARCHAR(50)	,
	@18			NVARCHAR(50)	
	AS
	IF NOT EXISTS(SELECT @1 FROM TblDOgs)
	BEGIN
	INSERT INTO TblDogs
	VALUES (@1, @2, @3, @4, @5, @6, @7, @8, @9, @10)
	INSERT INTO TblDogHealth
	VALUES (@1, @11, @12, @13, @14)
	INSERT INTO TblDogPedigree
	VALUES (@1, @15, @16, @17, @18)
	END
	GO